language: python
cache:
  - pip
  #directories:
  #- ./GeoLite2-City
python:
  - "3.4"
  - "3.5"
  - "3.6"
# command to install dependencies
install:
  - pip install -r requirements.txt
  - mkdir /var/lib/GeoIP
  - curl http://geolite.maxmind.com/download/geoip/database/GeoLite2-City.tar.gz -o GeoLite2-City.tar.gz && tar xf GeoLite2-City.tar.gz && mv GeoLite2-City_2* /var/lib/GeoIP/GeoLite2-City.mmdb 
# command to run tests
script:
  - python3 geoip.py & 
  - python3 test_geoip.py
